services:
  build:
    build:
      secrets:
        - .env
      args:
        - GODYL_VERSION=local
      target: build
    image: idelchi/godyl:build
    container_name: godyl
    hostname: godyl
    volumes:
      - .:/home/user/ws
    extra_hosts:
      - host:host-gateway
    working_dir: /home/user/ws
    networks:
      - godyl
    secrets:
      - .env

  final:
    extends: build
    working_dir: /home/user/
    image: idelchi/godyl:final
    build:
      secrets:
        - .env
      args:
        - GODYL_VERSION=local
      target: final

  bookworm-amd64:
    extends: build
    build:
      target: final
    platform: linux/amd64

  bookworm-amd32:
    extends: bookworm-amd64
    platform: linux/386

  bookworm-arm64:
    extends: bookworm-amd64
    platform: linux/arm64/v8

  bookworm-armv7:
    extends: bookworm-amd64
    platform: linux/arm/v7

  alpine-amd64:
    extends: build
    build:
      dockerfile: Dockerfile.alpine
      target: final

  alpine-amd32:
    extends: alpine-amd64
    platform: linux/386

  alpine-arm64:
    extends: alpine-amd64
    platform: linux/arm64/v8

  alpine-armv7:
    extends: alpine-amd64
    platform: linux/arm/v7

  code:
    build:
      dockerfile: Dockerfile.code
    pull_policy: if_not_present
    container_name: code
    hostname: godylcode
    env_file:
      - ai.env
    volumes:
      - .:/home/user/ws
    extra_hosts:
      - host:host-gateway
    working_dir: /home/user/ws
    networks:
      - godyl

networks:
  godyl:
    name: godyl
    driver: bridge

secrets:
  .env:
    file: ./.env
