defaults:
  output: ~/.local/bin
  exe:
    patterns:
      - "{{ .Exe.Name }}.*"
  fallbacks:
    - go
    - rust
  source:
    type: github
  hints:
    - pattern: "{{ .Exe.Name }}"
      weight: 1
