services:
  build:
    build:
      args:
        - GODYL_VERSION=local
      target: build
    pull_policy: if_not_present
    image: idelchi/godyl:dev
    container_name: godyl
    hostname: godyl
    volumes:
      - .:/home/user/ws
    extra_hosts:
      - host:host-gateway
    working_dir: /home/user/ws
    networks:
      - godyl-network

  bookworm:
    extends: build
    build:
      target: final
    platform: linux/amd64

  bookworm-amd32:
    extends: bookworm
    platform: linux/386

  bookworm-arm64:
    extends: bookworm
    platform: linux/arm64/v8

  bookworm-armv7:
    extends: bookworm
    platform: linux/arm/v5

  bookworm-armv5:
    extends: bookworm
    platform: linux/arm/6

  alpine:
    extends: build
    build:
      dockerfile: Dockerfile.alpine
      target: final

  alpine-amd32:
    extends: alpine
    platform: linux/386

  alpine-arm64:
    extends: alpine
    platform: linux/arm64/v8

  alpine-armv7:
    extends: alpine
    platform: linux/arm/v7

  alpine-armv6:
    extends: alpine
    platform: linux/arm/v6
networks:
  godyl-network:
    name: godyl-network
    driver: bridge
