package main

import (
	"embed"
	"fmt"
	"os"

	"github.com/Masterminds/semver/v3"
	"github.com/idelchi/godyl/internal/app"
)

// Global variable for CI stamping.
var version = "unknown - unofficial & generated by unknown"

//go:embed defaults.yml tools.yml internal/core/updater/scripts/*
var embeds embed.FS

func main() {
	versions, err := semver.NewVersion("v0.0.11-beta")

	fmt.Println(versions)
	fmt.Println(err)
	os.Exit(0)

	// Initialize the application with embedded files and version
	application := app.New(version, embeds)

	// Execute the application
	if err := application.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
}
