package main

import (
	"embed"
	"fmt"
	"os"

	"github.com/idelchi/godyl/internal/app"
)

// Global variable for CI stamping.
var version = "unknown - unofficial & generated by unknown"

//go:embed defaults.yml tools.yml internal/core/updater/scripts/*
var embeds embed.FS

func main() {
	// Initialize the application with embedded files and version
	application := app.New(version, embeds)

	// Execute the application
	if err := application.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
}
