// Package main is the entry point for the godyl tool manager application.
package main

import (
	"embed"
	"fmt"
	"os"
	"time"

	"github.com/idelchi/godyl/internal/app"
	"github.com/idelchi/godyl/internal/debug"
)

// Global variable for CI stamping.
var version = "unknown - unofficial & generated by unknown"

//go:embed defaults.yml tools.yml internal/updater/scripts/*
var embeds embed.FS

func main() {
	// gif := []byte{
	// 	'G', 'I', 'F', '8', '9', 'a', 0x01, 0x00, 0x01, 0x00, 0x80, 0x00, 0x00,
	// 	0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x21, 0xF9, 0x04, 0x01, 0x00, 0x00, 0x00, 0x00,
	// 	0x2C, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x02, 0x02, 0x44, 0x01, 0x00, 0x3B,
	// }
	// os.WriteFile("tr/c", gif, 0o644)
	// os.WriteFile("tr/e", []byte{'H', 'e', 'l', 'l', 'o', 0, 'W', 'o', 'r', 'l', 'd', '\n'}, 0o644)

	// files := files.Files{
	// 	"tr/a",
	// 	"tr/b",
	// 	"tr/c",
	// 	"tr/d",
	// 	"tr/e",
	// 	"D:\\DevEnv\\Go\\bin\\go.exe",
	// }

	// for _, file := range files {
	// 	ok := file.IsBinaryLike()
	// 	fmt.Printf("File: %s, IsBinaryLike: %t\n", file.Path(), ok)
	// }

	// os.Exit(0)

	// fs := files.New("include/lib/headers", "a.h", "b.h")
	// fs = append(fs, files.New("include/src/bin", "a.exe", "b.exe")...)

	// for _, file := range fs {
	// 	// fmt.Println(file.WithoutFolder("include/lib/headers"))
	// 	// fmt.Println(file.WithoutFolder("include/lib/headers/"))
	// 	relative, err := file.RelativeTo("include")
	// 	if err != nil {
	// 		fmt.Println(err)
	// 	} else {
	// 		fmt.Println(relative)
	// 	}
	// 	// relative, err = file.RelativeTo("include/lib/headers/")
	// 	// if err != nil {
	// 	// 	fmt.Println(err)
	// 	// } else {
	// 	// 	fmt.Println(relative)
	// 	// }
	// }

	// os.Exit(0)
	now := time.Now()
	// Execute the application
	if err := app.Execute(version, embeds); err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}

	elapsed := time.Since(now)

	debug.Debug("Execution completed in %s", elapsed)
}
