// Code generated by "string-enumer -t Match -o match_enumer___generated.go ."; DO NOT EDIT.
package hints

// validMatchValues contains a map of all valid Match values for easy lookup
var validMatchValues = map[Match]struct{}{
	Weighted: {},
	Required: {},
	Excluded: {},
}

// Valid validates if a value is a valid Match
func (v Match) Valid() bool {
	_, ok := validMatchValues[v]
	return ok
}

// MatchValues returns a list of all (valid) Match values
func MatchValues() []Match {
	return []Match{
		Weighted,
		Required,
		Excluded,
	}
}
