// Code generated by "string-enumer -t Type -o type_enumer___generated.go ."; DO NOT EDIT.
package hints

// validTypeValues contains a map of all valid Type values for easy lookup
var validTypeValues = map[Type]struct{}{
	Glob:       {},
	Regex:      {},
	GlobStar:   {},
	StartsWith: {},
	EndsWith:   {},
	Contains:   {},
}

// Valid validates if a value is a valid Type
func (v Type) Valid() bool {
	_, ok := validTypeValues[v]
	return ok
}

// TypeValues returns a list of all (valid) Type values
func TypeValues() []Type {
	return []Type{
		Glob,
		Regex,
		GlobStar,
		StartsWith,
		EndsWith,
		Contains,
	}
}
