// Code generated by "string-enumer -t Format -o format_enumer___generated.go ."; DO NOT EDIT.
package iutils

// validFormatValues contains a map of all valid Format values for easy lookup
var validFormatValues = map[Format]struct{}{
	JSON: {},
	YAML: {},
	ENV:  {},
}

// Valid validates if a value is a valid Format
func (v Format) Valid() bool {
	_, ok := validFormatValues[v]
	return ok
}

// FormatValues returns a list of all (valid) Format values
func FormatValues() []Format {
	return []Format{
		JSON,
		YAML,
		ENV,
	}
}
