// Code generated by "enumer -type=Level -output level_enumer___generated.go"; DO NOT EDIT.

package logger

import (
	"fmt"
	"strings"
)

const _LevelName = "SILENTDEBUGINFOWARNERRORALWAYS"

var _LevelIndex = [...]uint8{0, 6, 11, 15, 19, 24, 30}

const _LevelLowerName = "silentdebuginfowarnerroralways"

func (i Level) String() string {
	i -= -1
	if i < 0 || i >= Level(len(_LevelIndex)-1) {
		return fmt.Sprintf("Level(%d)", i+-1)
	}
	return _LevelName[_LevelIndex[i]:_LevelIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LevelNoOp() {
	var x [1]struct{}
	_ = x[SILENT-(-1)]
	_ = x[DEBUG-(0)]
	_ = x[INFO-(1)]
	_ = x[WARN-(2)]
	_ = x[ERROR-(3)]
	_ = x[ALWAYS-(4)]
}

var _LevelValues = []Level{SILENT, DEBUG, INFO, WARN, ERROR, ALWAYS}

var _LevelNameToValueMap = map[string]Level{
	_LevelName[0:6]:        SILENT,
	_LevelLowerName[0:6]:   SILENT,
	_LevelName[6:11]:       DEBUG,
	_LevelLowerName[6:11]:  DEBUG,
	_LevelName[11:15]:      INFO,
	_LevelLowerName[11:15]: INFO,
	_LevelName[15:19]:      WARN,
	_LevelLowerName[15:19]: WARN,
	_LevelName[19:24]:      ERROR,
	_LevelLowerName[19:24]: ERROR,
	_LevelName[24:30]:      ALWAYS,
	_LevelLowerName[24:30]: ALWAYS,
}

var _LevelNames = []string{
	_LevelName[0:6],
	_LevelName[6:11],
	_LevelName[11:15],
	_LevelName[15:19],
	_LevelName[19:24],
	_LevelName[24:30],
}

// LevelString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LevelString(s string) (Level, error) {
	if val, ok := _LevelNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LevelNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Level values", s)
}

// LevelValues returns all values of the enum
func LevelValues() []Level {
	return _LevelValues
}

// LevelStrings returns a slice of all String values of the enum
func LevelStrings() []string {
	strs := make([]string, len(_LevelNames))
	copy(strs, _LevelNames)
	return strs
}

// IsALevel returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Level) IsALevel() bool {
	for _, v := range _LevelValues {
		if i == v {
			return true
		}
	}
	return false
}
