package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"github.com/idelchi/godyl/internal/tools"
	"github.com/idelchi/godyl/internal/tools/sources"
	"github.com/idelchi/godyl/pkg/file"
	"github.com/idelchi/godyl/pkg/logger"
	"github.com/idelchi/godyl/pkg/pretty"
	"golang.org/x/sync/errgroup"
)

// Global variable for CI stamping.
var version = "unknown - unofficial & generated by unknown"

// result struct to hold the tool and any associated error.
type result struct {
	tool  *tools.Tool
	found file.File
	err   error
	msg   string
}

// App is the main application struct holding configuration and state.
type App struct {
	cfg       Config
	defaults  Defaults
	log       *logger.Logger
	toolsList tools.Tools
}

func main() {
	app := &App{}
	if err := app.run(); err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
}

// run is the main entry point of the application.
func (app *App) run() error {
	cfg, err := parseFlags()
	if err != nil {
		return fmt.Errorf("error parsing flags: %v", err)
	}
	app.cfg = cfg

	if err := app.cfg.Validate(); err != nil {
		return fmt.Errorf("error validating configuration: %v", err)
	}

	app.defaults = Defaults{}
	if err := app.defaults.Load(app.cfg.Defaults.Name()); err != nil {
		return fmt.Errorf("error loading defaults: %v", err)
	}
	app.defaults.Merge(app.cfg)

	if app.cfg.Update.Update {
		if err := app.processUpdate(); err != nil {
			return fmt.Errorf("error updating: %v", err)
		}
		return nil
	}

	app.log = logger.New(app.cfg.Log)

	toolsList, err := app.loadTools(app.cfg.Tools)
	if err != nil {
		return fmt.Errorf("error loading tools: %v", err)
	}
	app.toolsList = toolsList

	t, wt := splitTags(app.cfg.Tags)

	app.log.Info("*** ***")
	app.log.Info("godyl running with:")
	app.log.Info("*** ***")
	app.log.Info("platform:")
	app.log.Info(PrintJSON(app.defaults.Platform))
	app.log.Info("*** ***")

	if err := app.processTools(t, wt); err != nil {
		return err
	}

	return nil
}

// processUpdate handles the update process based on the configuration.
func (app *App) processUpdate() error {
	updater := GodylUpdater{
		Strategy: app.cfg.Update.Strategy,
		Defaults: app.defaults.Defaults,
	}

	if err := updater.Update(); err != nil {
		return err
	}

	return nil
}

// loadTools loads the tools configuration from the given path.
func (app *App) loadTools(path string) (tools.Tools, error) {
	var toolsList tools.Tools
	if err := toolsList.Load(path); err != nil {
		return toolsList, fmt.Errorf("loading tools from %q: %w", path, err)
	}

	return toolsList, nil
}

// processTools processes each tool in the tools list concurrently.
func (app *App) processTools(t []string, wt []string) error {
	// Create a channel to collect the results.
	resultCh := make(chan result)

	// Set up the errgroup and concurrency limit.
	g := errgroup.Group{}
	if app.cfg.Parallel > 0 {
		g.SetLimit(app.cfg.Parallel)
		app.log.Info("running with %d parallel downloads", app.cfg.Parallel)
	}

	// Create a WaitGroup to wait for the reading of results to finish.
	var wg sync.WaitGroup
	wg.Add(1) // One goroutine will be reading from the resultCh.

	// Start a separate goroutine to read from the result channel.
	go func() {
		defer wg.Done() // Signal that reading is done when this goroutine exits.
		for res := range resultCh {
			app.processResult(res)
		}
	}()

	// Start goroutines for each tool.
	for _, tool := range app.toolsList {
		g.Go(func() error {
			tool.ApplyDefaults(app.defaults.Defaults)

			if err := tool.Resolve(t, wt); err != nil {
				resultCh <- result{tool: &tool, err: err}
				return nil
			}

			if app.cfg.Dry {
				resultCh <- result{tool: &tool, err: nil}
				return nil
			}

			msg, found, err := tool.Download()
			resultCh <- result{tool: &tool, found: found, err: err, msg: msg}

			if err != nil {
				return nil
			}

			output, _, err := tool.Post.Install(sources.InstallData{Env: tool.Env})
			if err != nil {
				resultCh <- result{tool: &tool, err: err, msg: output}
			}

			return nil
		})
	}

	// Wait for all the goroutines to finish.
	if err := g.Wait(); err != nil {
		return fmt.Errorf("error processing tools: %v", err)
	}

	// Close the result channel since no more results will be sent.
	close(resultCh)

	// Wait for the reader to finish processing all the results.
	wg.Wait()

	return nil
}

// processResult processes the result from a tool operation.
func (app *App) processResult(res result) {
	tool := res.tool
	err := res.err
	msg := res.msg
	found := res.found
	app.log.Always(tool.Name)
	app.log.Debug("configuration:")
	app.log.Debug("-------")
	app.log.Debug(pretty.YAMLMasked(tool))
	app.log.Debug("-------")
	if err != nil {
		if errors.Is(err, tools.ErrAlreadyExists) || errors.Is(err, tools.ErrDoesNotHaveTags) || errors.Is(err, tools.ErrDoesHaveTags) || errors.Is(err, tools.ErrSkipped) {
			app.log.Warn("  %v", err)
		} else {
			app.log.Error("  failed to install")
			app.log.Error("configuration:")
			app.log.Error("-------")
			app.log.Error(pretty.JSONMasked(tool))
			app.log.Error("-------")
			app.log.Error("  %v", err)
			app.log.Error("  %s", msg)
		}
	} else {
		if tool.Version != "" {
			app.log.Info("  version: %s", tool.Version)
		}
		app.log.Info("  picked download %q", filepath.Base(tool.Path))
		if tool.Mode == "find" {
			app.log.Info("  picked file %q", found)
			app.log.Info("  installed successfully at %q", filepath.Join(tool.Output, tool.Exe.Name))
			if tool.Aliases != nil {
				app.log.Info("  symlinks:")
				for _, alias := range tool.Aliases {
					app.log.Info("    - %q\n", filepath.Join(tool.Output, alias))
				}
			}
		} else {
			app.log.Info("  extracted to %q", tool.Output)
		}
	}
}
