title: Godyl
description: "Asset downloader for GitHub & GitLab releases, URLs, and Go projects"
baseurl: "/godyl"
url: "https://idelchi.github.io"

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-default-layout

color_scheme: light

# Enable search
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links for the upper right navigation
aux_links:
  "Godyl on GitHub":
    - "//github.com/idelchi/godyl"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Sort order for navigation links
nav_sort: case_sensitive

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2025 idelchi. Distributed under the MIT License."

# Collections for organizing content
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  commands:
    permalink: "/commands/:path/"
    output: true

# Define which collections appear in the navigation
just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_fold: true
    commands:
      name: Commands
      nav_fold: true

# Heading anchor links
heading_anchors: true

# Enable copy code buttons
enable_copy_code_button: true

permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      render_with_liquid: false
  # 404 page
  - scope:
      path: "404-page.md"
    values:
      render_with_liquid: true

markdown: kramdown
