source 'https://rubygems.org'

gem "jekyll", "~> 4.4"
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jemoji"
gem "jekyll-include-cache"
gem "jekyll-default-layout"

group :jekyll_plugins do
  gem "jekyll-timeago", "~> 0.13.1"
end