name: docker

on:
  workflow_call:
    inputs:
      image:
        description: "Docker Image to build"
        default: ${{ github.repository }}
        required: false
        type: string
      tag:
        description: "Docker Image tag"
        default: ${{ github.ref_name }}
        required: false
        type: string
      args:
        description: "Docker build args"
        required: false
        type: string
      platforms:
        description: "Platforms to build (comma separated)"
        default: linux/amd64,linux/arm64,linux/arm/v7
        required: false
        type: string
      project:
        description: "Project name"
        default: ${{ github.event.repository.name }}
        required: false
        type: string
      cache:
        description: "Cache location for the Docker image"
        default: ${{ github.repository_owner }}/cache
        required: false
        type: string
      username:
        description: "Docker Hub Username"
        default: ${{ github.repository_owner }}
        required: false
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        description: "Docker Hub Token"
        required: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ inputs.platforms }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ inputs.username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ inputs.image }}:${{ inputs.tag }}
          target: final
          build-args: ${{ inputs.args }}
