name: release

on:
  workflow_dispatch:
  push:
    # For the release
    tags:
      - "*"
    # For the docker image
    # branches:
    #   - main

jobs:
  release:
    uses: idelchi/devenv/.github/workflows/gorelease.yml@dev
    if: startsWith(github.ref, 'refs/tags/') && !endsWith(github.ref, '-beta')
    permissions:
      contents: write
    with:
      config: .devenv/settings/.goreleaser.yaml

  docker:
    uses: idelchi/devenv/.github/workflows/docker.yml@dev
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: write
    secrets: inherit
    with:
      platforms: linux/amd64,linux/arm64
      args: |
        GODYL_VERSION=${{
          startsWith(github.ref, 'refs/tags/') && github.ref_name ||
          format('{0}:{1}', github.head_ref || github.ref_name, github.sha)
        }}
